title: Grace Christian Community
email: info@gracechristiancommunity.org.au
description: "God's vision for our city is that Melbourne might come to know and love Jesus - the one who knows and loves us."
keywords: "christianity, church, box hill, melbourne, protestant"
podcast_start: "Sat, 17 Jun 2023 13:00:00 +1000"
explicit: "False"

permalink: /:title
exclude:
  - "LICENSE"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "downloaded.txt"
  - "CNAME"
  - "temp"
include:
  - "_*.mp3"
