title: Podcast title
description: >-
  My description
permalink: /:title
channel_id: "UCDLAGQ0aCOzsDNqnVT30HSQ"
exclude:
  - "LICENSE"
  - "Gemfile"
  - "Gemfile.lock"
  - "main.py"
  - "requirements.txt"
include:
  - "_*.mp3"
